### ISSUE TITLE
This application is extremely insecure, due to the incorrect usage of JSON Web Tokens

### ISSUE THREAD

**Issue by Ratstail91** [kayode0x/Apexwallet-Backend#1]
I'm no expert, but I've built my own JWT-driven auth microservice which uses them correctly:

https://github.com/krgamestudios/auth-server

You should not be asking people to sign up to this project until your security is at least up to this standard (that being said, again I'm not an expert so there might be bugs that I'm unaware of; but I'm confident enough to use it myself).

If you'd like help getting to this point, I'd be happy to share my knowhow - this auth-server is actually part of a larger micro-service driven project called the MERN-template:

https://github.com/krgamestudios/MERN-template

I'm not saying this to crap on your work, rather I want to make sure you don't get into trouble due to your inexperience.

**Comment by kayode0x** [comment]
Thanks but I'll stick with one access token for this project. It's days of maintenance are also numbered.

**Comment by kayode0x** [comment]
Hi again, refresh tokens have been implemented, thanks.
