### ISSUE TITLE
email veirification

### ISSUE THREAD

**Issue by onoja123** [kayode0x/Apexwallet-Backend#6]
I noticed i can login without verifying my email after signup, its not picking the isVerified = false on the schema, please can you fix the issue, so if a user doesn’t verify his or her email , her or she wont be granted access to login

**Comment by onoja123** [comment]
Okay but can you please make that isActive turn to true when user verifies his email, because the boolean isActive still stays at false even after verifying

**Comment by kayode0x** [comment]
See: https://github.com/kayode0x/Apexwallet-Backend/blob/main/routes/authRoute.js#L280

**Comment by onoja123** [comment]
This is suppose to work, but when you check the database it doesn’t change to true, it only reads the first if condition

**Comment by kayode0x** [comment]
i just tried creating a new account, everything works fine. try requesting a new verification email, thanks.

**Comment by onoja123** [comment]
Okay thank you, 🙏
